### ISSUE TITLE
Docs, sidebars, and options

### ISSUE THREAD

**Issue by aa0pb** [mykle1/MMM-EarthWinds#1]
Howdy,

Cool module.  I have a few questions on it.

When I add it on my system sized to 300px x 300px there are scroll bars, how do you get rid of them?
Also if I click the earth button, it goes full screen, but how do I get back?

Is the a way to have it start over NA?  

I look forward to the module,  looks to be a fun one.

**Comment by mykle1** [comment]
It was designed to be a full screen live background that you would display your other modules on top of. I'm thinking you would be able to use css to your benefit. 

I'm struggling with getting the module to default to a specific location. I am in NA, as well. NYC. I'm glad you like it and I'm sorry your having trouble with it.
